apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-policy
  namespace: microservices
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: backend
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: frontend
      ports:
        - protocol: TCP
          port: 80
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: user-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: product-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: order-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: payment-service
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: notification-service
      ports:
        - protocol: TCP
          port: 80
