apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: orchestration-microservices
  namespace: argocd
spec:
  project: default
  revisionHistoryLimit: 5

  source:
    repoURL: https://github.com/roua2288/orchestration-microservices-.git
    targetRevision: main
    path: orchestration-app
    helm:
      releaseName: orchestration-app
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: microservices

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true