apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-application-sync
  namespace: default
rules:
  - apiGroups:
      - ""
      - "apps"
      - "autoscaling"
      - "argoproj.io"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-application-sync
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argocd-application-controller
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-application-sync