apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - microservices
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app.kubernetes.io/instance: orchestration-app
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
