apiVersion: v2
name: orchestration-app
description: Helm Umbrella Chart pour l'application microservices sur Amazon EKS
type: application
version: 0.2.0
appVersion: "2.0.0"

dependencies:
  - name: frontend
    version: 0.1.0
    repository: "file://../charts/frontend"
    condition: frontend.enabled

  - name: backend
    version: 0.1.0
    repository: "file://../charts/backend"
    condition: backend.enabled

  - name: user-service
    version: 0.1.0
    repository: "file://../charts/user-service"
    condition: user-service.enabled

  - name: product-service
    version: 0.1.0
    repository: "file://../charts/product-service"
    condition: product-service.enabled

  - name: order-service
    version: 0.1.0
    repository: "file://../charts/order-service"
    condition: order-service.enabled

  - name: payment-service
    version: 0.1.0
    repository: "file://../charts/payment-service"
    condition: payment-service.enabled

  - name: notification-service
    version: 0.1.0
    repository: "file://../charts/notification-service"
    condition: notification-service.enabled

  - name: postgresql
    alias: users-db
    version: 0.1.2
    repository: "file://../charts/postgresql"
    condition: users-db.enabled

  - name: postgresql
    alias: products-db
    version: 0.1.2
    repository: "file://../charts/postgresql"
    condition: products-db.enabled

  - name: postgresql
    alias: orders-db
    version: 0.1.2
    repository: "file://../charts/postgresql"
    condition: orders-db.enabled

  - name: postgresql
    alias: payments-db
    version: 0.1.2
    repository: "file://../charts/postgresql"
    condition: payments-db.enabled

  - name: postgresql
    alias: notifications-db
    version: 0.1.2
    repository: "file://../charts/postgresql"
    condition: notifications-db.enabled