databaseExternalSecrets:
  enabled: true
  refreshInterval: 1h

  databases:
    - targetSecretName: users-db-credentials
      remoteSecretName: orchestration/microservices/users-db

    - targetSecretName: products-db-credentials
      remoteSecretName: orchestration/microservices/products-db

    - targetSecretName: orders-db-credentials
      remoteSecretName: orchestration/microservices/orders-db

    - targetSecretName: payments-db-credentials
      remoteSecretName: orchestration/microservices/payments-db

    - targetSecretName: notifications-db-credentials
      remoteSecretName: orchestration/microservices/notifications-db

users-db:
  enabled: true
  fullnameOverride: users-db
  existingSecret: users-db-credentials
  database:
    name: users_db
    user: user_admin
    password: ""
  persistence:
    enabled: true
    storageClassName: gp3
    size: 5Gi

products-db:
  enabled: true
  fullnameOverride: products-db
  existingSecret: products-db-credentials
  database:
    name: products_db
    user: product_admin
    password: ""
  persistence:
    enabled: true
    storageClassName: gp3
    size: 5Gi

orders-db:
  enabled: true
  fullnameOverride: orders-db
  existingSecret: orders-db-credentials
  database:
    name: orders_db
    user: order_admin
    password: ""
  persistence:
    enabled: true
    storageClassName: gp3
    size: 5Gi

payments-db:
  enabled: true
  fullnameOverride: payments-db
  existingSecret: payments-db-credentials
  database:
    name: payments_db
    user: payment_admin
    password: ""
  persistence:
    enabled: true
    storageClassName: gp3
    size: 5Gi

notifications-db:
  enabled: true
  fullnameOverride: notifications-db
  existingSecret: notifications-db-credentials
  database:
    name: notifications_db
    user: notification_admin
    password: ""
  persistence:
    enabled: true
    storageClassName: gp3
    size: 5Gi

user-service:
  databaseSecretName: users-db-credentials

product-service:
  databaseSecretName: products-db-credentials

order-service:
  databaseSecretName: orders-db-credentials
  configMap:
    enabled: true
    data:
      APP_NAME: order-service
      APP_ENV: production
      AWS_REGION: eu-west-3
      LOG_LEVEL: info
      PRODUCT_SERVICE_URL: http://orchestration-app-product-service

payment-service:
  databaseSecretName: payments-db-credentials
  configMap:
    enabled: true
    data:
      APP_NAME: payment-service
      APP_ENV: production
      AWS_REGION: eu-west-3
      LOG_LEVEL: info
      ORDER_SERVICE_URL: http://orchestration-app-order-service

notification-service:
  databaseSecretName: notifications-db-credentials