{{- if and .Values.secret.enabled (not .Values.secret.managedExternally) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "frontend.fullname" . }}-secret
  labels:
    {{- include "frontend.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.stringData }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
