image:
  repository: postgres
  tag: "16-alpine"
  pullPolicy: IfNotPresent

database:
  name: application_db
  user: application_user
  password: change-me

service:
  port: 5432

persistence:
  enabled: true
  storageClassName: gp3
  accessMode: ReadWriteOnce
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

securityContext:
  runAsNonRoot: true
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

podAnnotations: {}

nodeSelector: {}

tolerations: []

affinity: {}