{{- if .Values.externalSecrets.enabled }}
{{- range .Values.externalSecrets.services }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $.Release.Name }}-{{ . }}-external-secret
  namespace: {{ $.Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ . }}
spec:
  refreshInterval: {{ $.Values.externalSecrets.refreshInterval | quote }}
  secretStoreRef:
    name: {{ $.Values.externalSecrets.storeName }}
    kind: ClusterSecretStore
  target:
    name: {{ $.Release.Name }}-{{ . }}-secret
    creationPolicy: Owner
  data:
    - secretKey: DEMO_USERNAME
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteSecretName }}
        property: DEMO_USERNAME
    - secretKey: DEMO_PASSWORD
      remoteRef:
        key: {{ $.Values.externalSecrets.remoteSecretName }}
        property: DEMO_PASSWORD
{{- end }}
{{- end }}